In [1]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

In [4]:
train_labels = list()
train_samples = list()

ThoughtProcess while creating this dataset.

-> Let’s suppose that an experimental drug was tested on individuals ranging from age 13 to 100 in a clinical trial. The trial had 2100 participants. Half of the participants were under 65 years old, and the other half was 65 years of age or older.

-> The trial showed that around 95% of patients 65 or older experienced side effects from the drug, and around 95% of patients under 65 experienced no side effects, generally showing that elderly individuals were more likely to experience side effects.

In [5]:
for i in range(50):
    # The ~5% of younger individuals who did experience side effects
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)

    # The ~5% of older individuals who did not experience side effects
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)

for i in range(1000):
    # The ~95% of younger individuals who did not experience side effects
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)

    # The ~95% of older individuals who did experience side effects
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(1)

In [13]:
print(len(train_samples),len(train_labels))

2100 2100


-> Next step is to transform this list into Numpy array

In [17]:
train_samples = np.array(train_samples)
train_labels = np.array(train_labels)

In [20]:
train_labels,train_samples = shuffle(train_labels,train_samples)

In [35]:
scaler = MinMaxScaler((0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [38]:
[scaled_train_samples[i] for i in range(5)]

[array([0.68965517]),
 array([0.75862069]),
 array([0.96551724]),
 array([0.89655172]),
 array([0.04597701])]