In [71]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler
import os

In [44]:
from sklearn.metrics import confusion_matrix,classification_report

In [45]:
train_labels = list()
train_samples = list()

ThoughtProcess while creating this dataset.

-> Let’s suppose that an experimental drug was tested on individuals ranging from age 13 to 100 in a clinical trial. The trial had 2100 participants. Half of the participants were under 65 years old, and the other half was 65 years of age or older.

-> The trial showed that around 95% of patients 65 or older experienced side effects from the drug, and around 95% of patients under 65 experienced no side effects, generally showing that elderly individuals were more likely to experience side effects.

In [46]:
for i in range(50):
    # The ~5% of younger individuals who did experience side effects
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)

    # The ~5% of older individuals who did not experience side effects
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)

for i in range(1000):
    # The ~95% of younger individuals who did not experience side effects
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)

    # The ~95% of older individuals who did experience side effects
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(1)

In [47]:
print(len(train_samples),len(train_labels))

2100 2100


-> Next step is to transform this list into Numpy array

In [48]:
train_samples = np.array(train_samples)
train_labels = np.array(train_labels)

In [49]:
train_labels,train_samples = shuffle(train_labels,train_samples)

In [50]:
scaler = MinMaxScaler((0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [51]:
for i in scaled_train_samples:
  print(i)

[0.14942529]
[0.8045977]
[0.09195402]
[0.08045977]
[0.62068966]
[0.93103448]
[0.1954023]
[0.70114943]
[0.56321839]
[0.26436782]
[0.72413793]
[0.44827586]
[0.89655172]
[0.44827586]
[0.12643678]
[0.17241379]
[0.2183908]
[0.71264368]
[0.25287356]
[0.54022989]
[0.25287356]
[0.63218391]
[0.36781609]
[0.1954023]
[0.08045977]
[0.72413793]
[0.25287356]
[0.6091954]
[0.32183908]
[0.24137931]
[0.24137931]
[0.27586207]
[0.67816092]
[0.45977011]
[0.70114943]
[0.64367816]
[0.90804598]
[0.71264368]
[0.85057471]
[0.1954023]
[0.56321839]
[0.59770115]
[0.73563218]
[0.7816092]
[0.36781609]
[0.73563218]
[0.29885057]
[0.98850575]
[0.59770115]
[0.68965517]
[0.]
[1.]
[0.25287356]
[0.97701149]
[0.63218391]
[0.11494253]
[0.20689655]
[0.64367816]
[0.74712644]
[0.14942529]
[0.91954023]
[0.71264368]
[0.37931034]
[0.01149425]
[0.08045977]
[0.7816092]
[0.86206897]
[0.04597701]
[0.57471264]
[0.54022989]
[0.98850575]
[0.36781609]
[0.82758621]
[0.94252874]
[0.98850575]
[0.02298851]
[0.04597701]
[0.43678161]
[0.9540229

In [52]:
type(train_labels[0])

numpy.int64

**2.  Create an Artificial Neural Network with TensorFlow's Keras API**

In [53]:
 
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation,Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [54]:
model = Sequential([
                    Dense(units=16,input_shape=(1,),activation='relu'),
                    Dense(units=32,activation='relu'),
                    Dense(units=2,activation='softmax')
])

In [55]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_4 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


**3. Train an Artificial Neural Network with TensorFlow's Keras API**

In [56]:
model.compile(optimizer='Adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

3. Build a Validation Set With TensorFlow's Keras API

In [57]:
model.fit(x=scaled_train_samples,y=train_labels,batch_size=10,validation_split=0.2,epochs=30,shuffle=True,verbose=2)

Epoch 1/30
168/168 - 0s - loss: 0.6285 - accuracy: 0.6292 - val_loss: 0.5057 - val_accuracy: 0.8500
Epoch 2/30
168/168 - 0s - loss: 0.4002 - accuracy: 0.8732 - val_loss: 0.3052 - val_accuracy: 0.9429
Epoch 3/30
168/168 - 0s - loss: 0.2927 - accuracy: 0.9226 - val_loss: 0.2550 - val_accuracy: 0.9429
Epoch 4/30
168/168 - 0s - loss: 0.2690 - accuracy: 0.9399 - val_loss: 0.2409 - val_accuracy: 0.9429
Epoch 5/30
168/168 - 0s - loss: 0.2613 - accuracy: 0.9339 - val_loss: 0.2345 - val_accuracy: 0.9405
Epoch 6/30
168/168 - 0s - loss: 0.2580 - accuracy: 0.9375 - val_loss: 0.2290 - val_accuracy: 0.9429
Epoch 7/30
168/168 - 0s - loss: 0.2544 - accuracy: 0.9435 - val_loss: 0.2249 - val_accuracy: 0.9429
Epoch 8/30
168/168 - 0s - loss: 0.2506 - accuracy: 0.9387 - val_loss: 0.2240 - val_accuracy: 0.9595
Epoch 9/30
168/168 - 0s - loss: 0.2492 - accuracy: 0.9411 - val_loss: 0.2207 - val_accuracy: 0.9429
Epoch 10/30
168/168 - 0s - loss: 0.2456 - accuracy: 0.9440 - val_loss: 0.2193 - val_accuracy: 0.9595

In [58]:
test_samples = list()
test_labels = list()

In [59]:
for i in range(50):
    # The ~5% of younger individuals who did experience side effects
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(1)

    # The ~5% of older individuals who did not experience side effects
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)

for i in range(1000):
    # The ~95% of younger individuals who did not experience side effects
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(0)

    # The ~95% of older individuals who did experience side effects
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(1)

In [60]:
test_samples = np.array(test_samples)
test_labels = np.array(test_labels)

In [61]:
scaled_test_samples = scaler.fit_transform(test_samples.reshape(-1,1))

In [62]:
model_pred = model.predict(scaled_test_samples,verbose=0,batch_size=10)

In [63]:
model_pred

array([[0.9612259 , 0.03877403],
       [0.04110682, 0.95889324],
       [0.5835076 , 0.41649237],
       ...,
       [0.02618328, 0.9738167 ],
       [0.96101767, 0.03898235],
       [0.09826842, 0.9017316 ]], dtype=float32)

In [64]:
rounded_pred = np.argmax(model_pred,axis=1)

In [65]:
rounded_pred

array([0, 1, 0, ..., 1, 0, 1])

In [66]:
print(confusion_matrix(test_labels,rounded_pred))
print(classification_report(test_labels,rounded_pred))

[[ 981   69]
 [  49 1001]]
              precision    recall  f1-score   support

           0       0.95      0.93      0.94      1050
           1       0.94      0.95      0.94      1050

    accuracy                           0.94      2100
   macro avg       0.94      0.94      0.94      2100
weighted avg       0.94      0.94      0.94      2100



MODEL SAVING

In [75]:
if os.path.isfile('model.h5') is False:
  model.save('model.h5')

INFO:tensorflow:Assets written to: model.sav/assets


In [76]:
from tensorflow.keras.models import load_model
new_model = load_model('model.h5')

In [78]:
new_model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_4 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [81]:
new_model.get_weights()

[array([[-0.45774987,  0.6706495 ,  0.48386085,  0.65718305, -0.20184019,
          0.04807584, -0.08573419, -0.3722246 , -0.01492637, -0.00400788,
          0.55513537,  0.57702076,  0.62072724, -0.47819275, -0.38799685,
          0.07736869]], dtype=float32),
 array([ 0.        , -0.13172679, -0.25603232, -0.3467193 ,  0.        ,
         0.21225062,  0.        ,  0.        ,  0.        ,  0.        ,
        -0.26210594, -0.3049806 , -0.3213214 ,  0.        ,  0.        ,
         0.13626033], dtype=float32),
 array([[ 8.04618597e-02, -3.42860043e-01, -2.14492723e-01,
         -6.90967143e-02,  2.25860983e-01,  7.78955519e-02,
         -2.45636106e-02, -1.73757210e-01,  2.78132945e-01,
         -1.66098699e-01,  1.43418968e-01, -3.19883943e-01,
          1.24217033e-01, -2.89707571e-01, -6.17360175e-02,
         -3.23717535e-01,  6.63537979e-02,  1.56286269e-01,
         -8.92671049e-02,  2.99656183e-01, -2.11990461e-01,
          3.07864279e-01,  1.57382816e-01,  2.43666857e-01,
 

-----------